.\" Man page for steam-price
.TH man 1 "july 2019" "1.0" "steam-price man page"

.SH NAME
steam-price \- shows a game's lowest recorded price on Valve's Steam plataform

.SH SYNOPSIS
steam-price [OPTION]... [PARAMETER]...

.SH DESCRIPTION
steam-price is a shell program that searches for game prices on Valve's Steam using Steam's own API and stores the lowest one found for each game.

.SH OPTIONS
-u    Updates the 'games to be searched' DB.

-g    Based on the output of -u, searches for and updates the price of every game listed if the new price is lower than current recorded one.

-q    Search for [PARAMETER] in Steam DB and return the lowest price ever found by the script if it was searched before.

-s    Like -gq but only downloads game information for names that match the [PARAMETER] that has been queried

.SH SEE ALSO
Source code available at https://github.com/gvs0709/Sistemas-Operacionais-2/tree/master/Trabalho-Final

.SH BUGS
Chars from some idioms that dont use ocidental alphabet might not be displayed properly

.SH REPORTING BUGS
Report any bugs at https://github.com/gvs0709/Sistemas-Operacionais-2/issues

.SH AUTORS
Gabriel V. Silveira (github: https://github.com/gvs0709) and Bruno B. Meurer (github: https://github.com/bmeurer1)
